modLoader="javafml"
loaderVersion="[36,37)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-Quark/issues"

[[mods]]
modId="dtquark"
version="${file.jarVersion}"
displayName="Dynamic Trees for Quark"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Quark.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Quark
'''
[[dependencies.dtquark]]
    modId="forge"
    mandatory=true
    versionRange="[36,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtquark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtquark]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtquark]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtquark]]
    modId="quark"
    mandatory=true
    versionRange="[r2.4-312,)"
    ordering="AFTER"
    side="BOTH"
